#!/usr/bin/env python

Import("env")

if "RD_GLSL" in env["BUILDERS"]:
     # make sure we recompile shaders if include files change
    inc_files = env.Glob("*_inc.glsl")
    for glsl_file in env.Glob("*.glsl"):
            if glsl_file in inc_files:
                continue
            env.Depends(env.RD_GLSL(glsl_file), inc_files)