#!/usr/bin/env python

Import("env")

from core.object import make_virtuals

env.Command(["gdvirtual.gen.inc"], [], Action(make_virtuals.run))

env_object = env.Clone()

env_object.add_source_files(env.core_sources, "*.cpp")
