#!/usr/bin/env python

Import("env")

env.add_source_files(env.servers_sources, "*.cpp")

SConscript("forward_clustered/SCsub", duplicate=0)
SConscript("forward_mobile/SCsub", duplicate=0)
SConscript("shaders/SCsub", duplicate=0)
