#!/usr/bin/env python

Import("env")

env.drivers_sources = []

# OS drivers
SConscript("unix/SCsub", duplicate=0)
SConscript("windows/SCsub", duplicate=0)

# Sounds drivers
SConscript("alsa/SCsub", duplicate=0)
SConscript("coreaudio/SCsub", duplicate=0)
SConscript("pulseaudio/SCsub", duplicate=0)
if env["platform"] == "windows":
    SConscript("wasapi/SCsub", duplicate=0)
if env["xaudio2"]:
    SConscript("xaudio2/SCsub", duplicate=0)

# Midi drivers
SConscript("alsamidi/SCsub", duplicate=0)
SConscript("coremidi/SCsub", duplicate=0)
SConscript("winmidi/SCsub", duplicate=0)

# Graphics drivers
if env["vulkan"]:
    SConscript("vulkan/SCsub", duplicate=0)
if env["opengl3"]:
    SConscript("gl_context/SCsub", duplicate=0)
    SConscript("gles3/SCsub", duplicate=0)

# Core dependencies
SConscript("png/SCsub", duplicate=0)
SConscript("spirv-reflect/SCsub", duplicate=0)

env.add_source_files(env.drivers_sources, "*.cpp")

lib = env.add_library("drivers", env.drivers_sources)
env.Prepend(LIBS=[lib])
