#!/usr/bin/env python

Import("env")

# Thirdparty source files

thirdparty_dir = "#thirdparty/spirv-reflect/"
thirdparty_sources = [
    "spirv-reflect/spirv_reflect.c",
]

env_thirdparty = env.Clone()
env_thirdparty.VariantDir("spirv-reflect", env.Dir(thirdparty_dir), duplicate=0)
env_thirdparty.disable_warnings()

env_thirdparty.add_source_files(env.drivers_sources, thirdparty_sources)
